import { readFileSync } from "node:fs";

// Generated by the rules-driven voyage in tests/game.test.js. Browser use proves
// the final UI boundary, not physical combat in every preceding mission.
export function endingCheckpoint() {
	return readFileSync(
		new URL("../fixtures/earned-epilogue.json", import.meta.url),
		"utf8",
	);
}
